### ISSUE TITLE
g.find is not a function.

### ISSUE THREAD

**Issue by Abbath** [haskell/vscode-haskell#272]
After installing the extension and opening any Haskell project sometimes I see a notification `g.find is not a function`.  It is probably from https://github.com/haskell/vscode-haskell/blob/5178445a707cd170a8761485abdedfd0bce7cc00/src/hlsBinaries.ts#L181
After that, the extension does not start at all.

My setup:
GHC-8.8.4
Kubuntu 20.04
vscode 1.47.3

**Comment by bubba** [comment]
I presume something wrongs going with the GitHub request and it's giving a bum error message

**Comment by alaendle** [comment]
@bubba: At least I face the same error message, already using version 1.1.0 of the plugin.
@Abbath: Does v1.1.0 solved this issue for you?

My setup:
Windows 10
VSCode: 1.47.3
GHC 8.8.3

**Comment by bapcyk** [comment]
the same in all last 3 versions.

**Comment by alaendle** [comment]
It seems to hit corporate users with single IP - at least the response from the API call returns` {"message":"API rate limit exceeded for xxx.xxx.xxx.xxx. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)","documentation_url":"https://developer.github.com/v3/#rate-limiting"}` sometimes for me; unfortunately the code interprets this as a successful API call and tries to extract the release information - leading to the mentioned error message.

**Comment by bubba** [comment]
@alaendle I was relying on the assumption that nobody would launch the extension more than 60 times in one hour, but with a single IP this is definitely going to be an issue. I wonder if we might need to create some sort of server that acts a proxy to pull down the latest release information? Logging in and authentication is most likely overkill.

Or perhaps if we hit the rate limit, we could fall back to just scraping the releases page instead of using the API?

**Comment by alaendle** [comment]
@bubba It's certainly not the case that the extension is launched more than 60times an hour; but my guess is that a lot of tools nowadays use the github API - so for me it would be absolutely o.k. is this error is just swallowed; it is relatively rare, but annoying since the extension isn't working if the rate limit is hit (even if there is no new release). So if it is just ignored, the next start of the extension would find the new release (if available) - or is this problematic because the extension and binary releases are tightly coupled and can only be updated as a pair? Then for sure a more advanced solution is needed - but maybe it is just o.k. to show some warning if there is a version mismatch? This is fore sure just my personal opinion - just workaround this corner case as simple as possible; scraping the release page or mirroring the release information might lead to other/new problems. But for sure any solution is welcome 😀
