### ISSUE TITLE
Cleanup executables from old releases

### ISSUE THREAD

**Issue by WorldSEnder** [haskell/vscode-haskell#273]
The current output of `ls -lh` on the `globalStoragePath` directory produces for me

```
-rwxr--r-- 1 u u 114M 29. Jul 20:52 haskell-language-server-0.2.2-linux-8.8.3
-rwxr--r-- 1 u u 116M 30. Jul 02:52 haskell-language-server-0.2.2-linux-8.10.1
-rwxr--r-- 1 u u 122M 11. Aug 07:45 haskell-language-server-0.3.0-linux-8.8.3
-rwxr--r-- 1 u u 123M 11. Aug 07:50 haskell-language-server-0.3.0-linux-8.10.1
-rwxr--r-- 1 u u 4,8M 11. Aug 07:45 haskell-language-server-wrapper-0.3.0-linux
-rwxr--r-- 1 u u 4,8M 29. Jul 20:52 haskell-language-server-wrapper-0.2.2-linux
```

As can be seen, old releases of `haskell-language-server`, that will never be required again, are just taking up a decent amount of diskspace (~240MB), that will only get worse over time. There should be a policy to remove any older versions of the wrapper, perhaps when downloading a newer one.

**Comment by leiftw** [comment]
Had not found this when opening https://github.com/haskell/vscode-haskell/issues/346 (which refers to Windows, the folder content is slightly different).
I second this. Nobody needs more applications that waste gigabytes per year!

**Comment by jneira** [comment]
@lylek suggested [here](https://github.com/haskell/vscode-haskell/issues/346#issuecomment-786122525):

> May I humbly suggest a menu item to purge all versions except the one(s) being used in open workspaces? That way folks don't have to know the path where they're stored. They can just, maybe once a year, run the cleanup option. And if it deletes a version they need for some workspace they don't have open - no big deal, it will re-download that version when they open it.

**Comment by jneira** [comment]
I've changed the title to `Cleanup executables from older releases` as afaiu the extension will not use older version of the hls executable itself.
Automatic deleting files is a delicate operation that can fail due to multiple reasons, even if the user has permissions to do it. We should ask user before doing it and handle the possible error.
What about warn about the existence of older versions in `globalStoragePath` after dowload a new version, mentioning the path to help user deleting manually the files they dont want?

**Comment by cptwunderlich** [comment]
I would also suggest to simply delete older HLS versions. Optionally, one could add a config option "keep n old versions".
I just discovered this by chance and saw that I have _17_ versions of HLS lying around...

**Comment by jneira** [comment]
It worths to note that due to deprecation of ghc support in haskell-language-server, new versions of the server might not support some ghc versions. Keep old versions of hls with support for those deprecated ghc's could help to neing able to load actual projects.
Although we aim to donwload automatically those hls versions: #454

**Comment by cptwunderlich** [comment]
I would say, when vscode-haskell downloads a new HLS version for GHC xyz, _then_ it can delete the old HLS version for GHC xyz.
So, when the user upgrades GHC, this may leave one old HLS version per old GHC version, but at least we don't have 10 HLS' with the _same_ GHC version.
(Or maybe keep 2 version per GHC version, if the new HLS is broken as a fallback?)

You can then add an Extension command to open the folder for manual cleaning, or something similar.

**Comment by jneira** [comment]
Last version of the extension has support for download/use older version of hls it they supports the ghc required for the project loaded. That is a nice feature but if makes more complex an eventuak automatic cleaning. It will download again the appropiate hls though.

**Comment by fendor** [comment]
Old executables can not be cleaned up by using ghcup. No further actions required here.
