### ISSUE TITLE
Be able to stop the server entirely

### ISSUE THREAD

**Issue by dnikolovv** [haskell/vscode-haskell#320]
Often times the server just decides to hang or just simply not work. In these cases it's usually handy to resort to ghci or `stack build --file-watch`.

The problem is that when the server hangs you cannot use `stack` due to it also hanging due to a lock `blocking for directory lock on /home/some/path/.stack-work/dist/x86_64-linux/Cabal-3.0.1.0/build-lock`.

Sometimes you just want to quit trying to make the language server work and simply use VS Code + a separate terminal. It'd be nice if there was a command that shuts down the server entirely.

I haven't found a sane workaround so far.

**Comment by jneira** [comment]
The first workaround i can think of is to disable the extension (cause it is useless without a running server) for that workspace and kill the server process externally but i guess it would be included in the insane ones.

**Comment by dnikolovv** [comment]
@jneira Haha! I do exactly that! It kind of ruins the UX although I've been going with it for a while now lol.

**Comment by dnikolovv** [comment]
This issue is actually mostly related to https://github.com/haskell/ghcide/issues/842. This has been the most common cause of the server refusing to work.

**Comment by anka-213** [comment]
I just wanted this again when I was trying to do a `git bisect run`, since there's a lot of needless busywork that hls does when the files changes a lot all the time.

Disabling the extension is kind of annoying because it forces you to reload the editor. What I really want is a command, like the " Restart Haskell LSP server", but "Stop Haskell LSP server" as an easy way of temporarily stopping the server.

The main workaround I've been using is to set `haskell.serverExecutablePath` to something that doesn't exist or to `false` or something, but that's not a great workaround either.

**Comment by jneira** [comment]
https://github.com/haskell/vscode-haskell/releases/tag/1.5.1 has included two new commands: `Start Haskell LSP server` and `Stop Haskell LSP server`
I had no time to test them properly as the release fixed a bug but let me know if they work for you if you got the chance to check them
