### ISSUE TITLE
Support new hls generic plugin configuration

### ISSUE THREAD

**Issue by jneira** [haskell/vscode-haskell#336]
* Some insights in the emacs side: https://github.com/emacs-lsp/lsp-haskell/issues/99
* Taken form that issue: 

> With haskell/haskell-language-server#691 we are introducing a boilerplate style of configuration per plugin, where each gets a global on/off switch, as well as being able to individually turn off parts of a plugin.
> 
> At some (hopefully soon) point we will be able to install a custom set of plugins (as proposed here).
> 
> So I think we need a meta-config, which can be provided with a list of plugins that are installed in the HLS exe, and generates customization and config entries for each of them.

//cc @alanz @bubba

**Comment by berberman** [comment]
What about adding a "custom" section so that users could configure it temporarily using JSON?

![image](https://user-images.githubusercontent.com/26041945/106581187-8e70b300-657d-11eb-9e05-ba425a3b72b7.png)

This should not be the final solution, but the expressiveness of configuration options provided by vscode UI is fairly limited. My idea is that the custom section could be "merged" with other options, but it seems that this merge is hard to be done in the vscode side, since we simply pass the section name like this to setup a listener on the configuration:

https://github.com/haskell/vscode-haskell/blob/b419317f1539b2fe9b9a13fc5710c1d222d3eba8/src/extension.ts#L217

but the underlying logic to obtain the real configuration is opaque:

https://github.com/microsoft/vscode-languageserver-node/blob/3c5d4bef4fb4ed85d5c8db8da6f18bf55a44b9a1/client/src/common/client.ts#L2480

Will this approach be reasonable if the merge should be done in the server side?

**Comment by jneira** [comment]
Mmm if we have to do the merge in the server i would wait to a definitive solution, with the possible options fixed if possible

**Comment by jneira** [comment]
I am on working on this, taking the minimal configuration to be added in https://github.com/haskell/haskell-language-server/issues/1433
