### ISSUE TITLE
Intend to contributing VSCode extension https://github.com/complyue/vscode-ghci

### ISSUE THREAD

**Issue by complyue** [haskell/vscode-haskell#384]
Greetings!

I have just finished the preview version of https://github.com/complyue/vscode-ghci

It seeks to provide simple but convenient ways to run Haskell snippets in `.hs` source files (and maybe dedicated `.hsi` script files in the future?), those snippets are simply marked as VSCode CodeLens cells with `-- %%` comments.

Some demo screenshots here: https://github.com/complyue/vscode-ghci/issues/1

The demo project here: https://github.com/complyue/GHCiCode

The demo project also includes artifacts for [Gitpod](https://gitpod.io) to automatically setup ghcup/ghc/cabal/stack as a cloud based workspace, a single click launch URL: https://gitpod.io/#https://github.com/complyue/GHCiCode

[![Open in Gitpod](https://gitpod.io/button/open-in-gitpod.svg)](https://gitpod.io/#https://github.com/complyue/GHCiCode)

As I see it, [Gitpod](https://gitpod.io) & the upcoming [Github Codespaces](https://github.com/features/codespaces) will be great options for Windows & ChromOS users wrt Haskell development on-the-go.

I would like https://github.com/complyue/vscode-ghci to live in the https://github.com/haskell organization so more maintainers & contributors from the community can develop and maintain it together.

What do you think?

**Comment by ndmitchell** [comment]
Hey @complyue - that seems cool. Most projects start outside of the Haskell organisation, and then only migrate into the org once they have gained a critical mass. For example, the Haskell IDE stuff lived outside the Haskell org for many years first. I'd be inclined to take the same approach with your new project - that shouldn't stop anyone contributing since you can just add additional contributors, or even create your own org for the project.

**Comment by complyue** [comment]
Fair enough, let's see if this little feature will go popular enough to need that wide collaboration by living in here.

**Comment by jneira** [comment]
Good luck, i am gonna close this one if you dont mind
