### ISSUE TITLE
Formatter no longer works with version 2.2.2

### ISSUE THREAD

**Issue by mistyharsh** [haskell/vscode-haskell#787]
## Summary
VS Code doesn't recognize `vscode-haskell` extension as a formatter for Haskell.

### Your environment

Which OS do you use:
MacOS

### Steps to reproduce
Nothing much. Just update the VS Code extension to the latest version 2.2.2.

### Expected behaviour
After setting the formatter (default or otherwise), the Format Document command should format the document.

### Actual behaviour
VS Code complains that Formatter is not installed.

![image](https://user-images.githubusercontent.com/4905303/208483278-b5097b70-919d-49c2-9ca3-e158adf69257.png)

Even with manually specifying the settings, it doesn't work.

```json
{
  "editor.defaultFormatter": "haskell.haskell",
  "haskell.formattingProvider": "ormolu"
}
```

**Comment by fendor** [comment]
Hi,
thank you for your bug report!

Are you sure the extension is correctly installed? If yes, please follow the instructions here: https://github.com/haskell/vscode-haskell#investigating-and-reporting-problems

and provide the logs here so we can take a closer look

**Comment by mistyharsh** [comment]
Thanks for the reply.
This is the log file - [log-file.log](https://github.com/haskell/vscode-haskell/files/10270669/log-file.log).

I hope that helps!

**Comment by fendor** [comment]
Yep that helps!
It seems that you are using GHC 9.4.2 and HLS 1.8.0.0 with GHC 9.4.2 does not support any formatter.

Ways forward: wait for the [next release of HLS](https://github.com/haskell/haskell-language-server/pull/3409/files#diff-8f5b98c14f8d7b980d7e0c94d8f49fddc3386ba8f0a031b66e2c0df81edf0c5e) to bring support for more formatters in GHC 9.4.2, or downgrade your GHC version for your project, either by instructing cabal to use an older GHC version or instruct ghcup to set an older GHC version via `ghcup set ghc <older-version>`.
I fear, until the release, the only other sensible version is `8.10.7`. Probably waiting for the release is the best idea, since then you can use `9.2.5`, which is the currently best version for MacOS. You may also install a fitting HLS version for GHC 9.2.5 right away via:
```
ghcup compile hls --ghc 9.2.5 -g master --git-describe-version
```

**Comment by mistyharsh** [comment]
Thanks @fendor. I understand the issue.
I would try the suggestions. I would close the issue now!
