### ISSUE TITLE
Cannot format `.cabal` files with HLS 1.9

### ISSUE THREAD

**Issue by openingnow** [haskell/vscode-haskell#791]
### Your environment

Which OS do you use: Arch(WSL2) GHC 9.2.5 HLS 1.9.0.0 | Oracle linux aarch64 GHC 9.2.5, 9.4.4 HLS 1.9.0.0
all installed with ghcup

### Steps to reproduce
1. open `foo.cabal` file
1. Press alt+shift+f to format

### Expected behaviour
Format document with `cabal-fmt` plugin https://github.com/haskell/haskell-language-server/pull/2047

### Actual behaviour
Popup window saying `There is no formatter for 'cabal' files installed.`

```sh
$ haskell-language-server-wrapper --version
haskell-language-server version: 1.9.0.0 (GHC: 9.4.4) (PATH: /home/opc/.ghcup/hls/1.9.0.0/lib/haskell-language-server-1.9.0.0/bin/haskell-language-server-wrapper)
$ haskell-language-server-wrapper --list-plugins 2>&1 | grep cabalfmt
cabalfmt
```

**Comment by fendor** [comment]
Hi! 
While support is indeed advertised, vscode doesn't work with it yet, it requires the PR #618 and a release.
However, that isn't trivial because then suddenly vscode doesn't properly work with older HLS versions (if you do require so). 
Haven't figured out the best way forward, and I am not available for implementing features for the next two weeks, so it will have to rest until then. If you have a good idea and time to implement it, happy to merge it.

**Comment by openingnow** [comment]
Didn't know that related PR exists. Feel free to close this if it seems duplicated.

IMHO making a pre-release would be fine as it needs explicit participation.

**Comment by openingnow** [comment]
Now works fine with pre-release 2.5.0, although external installation is needed.
